# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

default: &default
  track_playhead:
    class: TrackPlayheadJob
    queue: high_priority
    schedule: every 30 seconds

  update_state:
    class: UpdateStateJob
    queue: high_priority
    schedule: every minute

  sync_queue_playlist:
    class: SyncQueuePlaylistJob
    queue: default
    schedule: every 5 minutes

  clear_old_song_requests:
    class: ClearOldSongRequestsJob
    queue: background
    schedule: every hour

  refresh_spotify_tokens:
    class: RefreshSpotifyTokensJob
    queue: default
    schedule: every 1 hour

development:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
